// packages/ui-react/src/index.tsx
import * as React from 'react';
import { createComponent } from '@lit/react';
import {
  GeraldoBadge as GeraldoBadgeElement,
  GeraldoButton as GeraldoButtonElement,
  GeraldoCard as GeraldoCardElement,
  GeraldoCheckbox as GeraldoCheckboxElement,
  GeraldoRadio as GeraldoRadioElement,
  GeraldoRadioGroup as GeraldoRadioGroupElement,
  GeraldoSwitch as GeraldoSwitchElement,
  GeraldoText as GeraldoTextElement,
  GeraldoTextField as GeraldoTextFieldElement,
  GERALDO_RADIO_SELECT,
  defineGeraldoUI,
} from '@aiqfome-sdk/ui-lit';

export { defineGeraldoUI };
export { geraldoSpace, geraldoSpaceVar, type GeraldoSpace } from '@aiqfome-sdk/themes';
export type {
  GeraldoBadgeTone,
  GeraldoButtonColor,
  GeraldoButtonSize,
  GeraldoButtonVariant,
  GeraldoCardElevation,
  GeraldoTextVariant,
  GeraldoTextWeight,
} from '@aiqfome-sdk/ui-lit';

/** Call once before rendering React components that use Geraldo custom elements. */
export function setupAiqfomeUI(): void {
  defineGeraldoUI();
}

export const GeraldoButton = createComponent({
  tagName: 'geraldo-button',
  elementClass: GeraldoButtonElement,
  react: React,
});

export const GeraldoText = createComponent({
  tagName: 'geraldo-text',
  elementClass: GeraldoTextElement,
  react: React,
});

export const GeraldoBadge = createComponent({
  tagName: 'geraldo-badge',
  elementClass: GeraldoBadgeElement,
  react: React,
});

export const GeraldoCard = createComponent({
  tagName: 'geraldo-card',
  elementClass: GeraldoCardElement,
  react: React,
});

export const GeraldoTextField = createComponent({
  tagName: 'geraldo-text-field',
  elementClass: GeraldoTextFieldElement,
  react: React,
  events: {
    onGeraldoInput: 'geraldo-input',
    onGeraldoChange: 'geraldo-change',
  },
});

export const GeraldoCheckbox = createComponent({
  tagName: 'geraldo-checkbox',
  elementClass: GeraldoCheckboxElement,
  react: React,
  events: {
    onGeraldoChange: 'geraldo-change',
  },
});

export const GeraldoRadio = createComponent({
  tagName: 'geraldo-radio',
  elementClass: GeraldoRadioElement,
  react: React,
  events: {
    onGeraldoChange: 'geraldo-change',
    onGeraldoRadioSelect: GERALDO_RADIO_SELECT,
  },
});

export const GeraldoRadioGroup = createComponent({
  tagName: 'geraldo-radio-group',
  elementClass: GeraldoRadioGroupElement,
  react: React,
  events: {
    onGeraldoChange: 'geraldo-change',
  },
});

export const GeraldoSwitch = createComponent({
  tagName: 'geraldo-switch',
  elementClass: GeraldoSwitchElement,
  react: React,
  events: {
    onGeraldoChange: 'geraldo-change',
  },
});

// packages/ui-lit/src/index.ts
/**
 * Geraldo UI — register all custom elements (idempotent).
 * Import `@aiqfome-sdk/themes/tokens.css` once in your app root before components.
 */

export { GeraldoButton } from './components/button/geraldo-button.js';
export type {
  GeraldoButtonVariant,
  GeraldoButtonColor,
  GeraldoButtonSize,
} from './components/button/geraldo-button.js';

export { GeraldoText } from './components/typography/geraldo-text.js';
export type { GeraldoTextVariant, GeraldoTextWeight } from './components/typography/geraldo-text.js';

export { GeraldoBadge } from './components/badge/geraldo-badge.js';
export type { GeraldoBadgeTone } from './components/badge/geraldo-badge.js';

export { GeraldoCard } from './components/card/geraldo-card.js';
export type { GeraldoCardElevation } from './components/card/geraldo-card.js';

export { GeraldoTextField } from './components/text-field/geraldo-text-field.js';

export { GeraldoCheckbox } from './components/checkbox/geraldo-checkbox.js';

export { GeraldoRadio, GERALDO_RADIO_SELECT } from './components/radio/geraldo-radio.js';
export { GeraldoRadioGroup } from './components/radio/geraldo-radio-group.js';

export { GeraldoSwitch } from './components/switch/geraldo-switch.js';

export { geraldoSpace, geraldoSpaceVar } from '@aiqfome-sdk/themes';
export type { GeraldoSpace } from '@aiqfome-sdk/themes';

import { GeraldoButton } from './components/button/geraldo-button.js';
import { GeraldoText } from './components/typography/geraldo-text.js';
import { GeraldoBadge } from './components/badge/geraldo-badge.js';
import { GeraldoCard } from './components/card/geraldo-card.js';
import { GeraldoTextField } from './components/text-field/geraldo-text-field.js';
import { GeraldoCheckbox } from './components/checkbox/geraldo-checkbox.js';
import { GeraldoRadio } from './components/radio/geraldo-radio.js';
import { GeraldoRadioGroup } from './components/radio/geraldo-radio-group.js';
import { GeraldoSwitch } from './components/switch/geraldo-switch.js';

const definitions: ReadonlyArray<readonly [string, CustomElementConstructor]> = [
  ['geraldo-button', GeraldoButton],
  ['geraldo-text', GeraldoText],
  ['geraldo-badge', GeraldoBadge],
  ['geraldo-card', GeraldoCard],
  ['geraldo-text-field', GeraldoTextField],
  ['geraldo-checkbox', GeraldoCheckbox],
  ['geraldo-radio', GeraldoRadio],
  ['geraldo-radio-group', GeraldoRadioGroup],
  ['geraldo-switch', GeraldoSwitch],
];

/** Register every Geraldo custom element if not already defined. */
export function defineGeraldoUI(): void {
  for (const [tag, ctor] of definitions) {
    if (!customElements.get(tag)) {
      customElements.define(tag, ctor);
    }
  }
}
